-- MySQL Script generated by MySQL Workbench
-- Mon Jan  9 19:07:54 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`table1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`table1` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`driver`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`driver` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `license` TINYINT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `iddriver_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`car_shop`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`car_shop` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `location` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`car`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`car` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `model` VARCHAR(45) NOT NULL,
  `vendor` VARCHAR(45) NOT NULL,
  `driver` INT NOT NULL,
  `car_shop` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_car_driver_idx` (`driver` ASC) VISIBLE,
  INDEX `fk_car_car_shop1_idx` (`car_shop` ASC) VISIBLE,
  CONSTRAINT `fk_car_driver`
    FOREIGN KEY (`driver`)
    REFERENCES `mydb`.`driver` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_car_car_shop1`
    FOREIGN KEY (`car_shop`)
    REFERENCES `mydb`.`car_shop` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`service_centre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`service_centre` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `order` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `location` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`service_centre_order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`service_centre_order` (
  `id` INT NOT NULL,
  `service_centre_id` INT NOT NULL,
  `car_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_service_centre_has_car_car1_idx` (`car_id` ASC) VISIBLE,
  INDEX `fk_service_centre_has_car_service_centre1_idx` (`service_centre_id` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `fk_service_centre_has_car_service_centre1`
    FOREIGN KEY (`service_centre_id`)
    REFERENCES `mydb`.`service_centre` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_service_centre_has_car_car1`
    FOREIGN KEY (`car_id`)
    REFERENCES `mydb`.`car` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`customer` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `is_driver` TINYINT NULL,
  `service_centre_order` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_customer_service_centre_order1_idx` (`service_centre_order` ASC) VISIBLE,
  CONSTRAINT `fk_customer_service_centre_order1`
    FOREIGN KEY (`service_centre_order`)
    REFERENCES `mydb`.`service_centre_order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`customer_car_shop`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`customer_car_shop` (
  `customer_id` INT NOT NULL,
  `car_shop_id` INT NOT NULL,
  `period` INT NOT NULL,
  PRIMARY KEY (`customer_id`, `car_shop_id`),
  INDEX `fk_customer_has_car_shop_car_shop1_idx` (`car_shop_id` ASC) VISIBLE,
  INDEX `fk_customer_has_car_shop_customer1_idx` (`customer_id` ASC) VISIBLE,
  CONSTRAINT `fk_customer_has_car_shop_customer1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `mydb`.`customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_customer_has_car_shop_car_shop1`
    FOREIGN KEY (`car_shop_id`)
    REFERENCES `mydb`.`car_shop` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`customer_service_centre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`customer_service_centre` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `service_centre` INT NOT NULL,
  `customer` INT NOT NULL,
  `period` VARCHAR(45) NOT NULL,
  INDEX `fk_service_centre_has_customer_customer1_idx` (`customer` ASC) VISIBLE,
  INDEX `fk_service_centre_has_customer_service_centre1_idx` (`service_centre` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_service_centre_has_customer_service_centre1`
    FOREIGN KEY (`service_centre`)
    REFERENCES `mydb`.`service_centre` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_service_centre_has_customer_customer1`
    FOREIGN KEY (`customer`)
    REFERENCES `mydb`.`customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`details_shop`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`details_shop` (
  `id` INT UNSIGNED NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `location` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`detail` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NULL,
  `price` VARCHAR(45) NOT NULL,
  `details_shop` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_detail_details_shop1_idx` (`details_shop` ASC) VISIBLE,
  CONSTRAINT `fk_detail_details_shop1`
    FOREIGN KEY (`details_shop`)
    REFERENCES `mydb`.`details_shop` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`details_shop_has_customer_service_centre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`details_shop_has_customer_service_centre` (
  `details_shop_id` INT UNSIGNED NOT NULL,
  `customer_service_centre_id` INT NOT NULL,
  PRIMARY KEY (`details_shop_id`, `customer_service_centre_id`),
  INDEX `fk_details_shop_has_customer_service_centre_customer_servic_idx` (`customer_service_centre_id` ASC) VISIBLE,
  INDEX `fk_details_shop_has_customer_service_centre_details_shop1_idx` (`details_shop_id` ASC) VISIBLE,
  CONSTRAINT `fk_details_shop_has_customer_service_centre_details_shop1`
    FOREIGN KEY (`details_shop_id`)
    REFERENCES `mydb`.`details_shop` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_details_shop_has_customer_service_centre_customer_service_1`
    FOREIGN KEY (`customer_service_centre_id`)
    REFERENCES `mydb`.`customer_service_centre` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `mydb` ;

-- -----------------------------------------------------
-- Placeholder table for view `mydb`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`view1` (`id` INT);

-- -----------------------------------------------------
-- View `mydb`.`view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`view1`;
USE `mydb`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
